### ISSUE TITLE
please build for 6 i lov these!

### ISSUE THREAD

**Issue by jph-wacheski** [wlaub/vcv#4]
these are very useful modules,. nicely made and functional,. please make a build for Rack 6.0.

**Comment by wlaub** [comment]
I've just pushed a v6 branch, which should build on the latest version. The front panels are messed up in a lot of places (some knob sizes changed or something), but everything should basically work now. UI fixes will have to wait for now.

**Comment by wlaub** [comment]
All modules are now converted to 0.6 and merged into master.
