### ISSUE TITLE
Windows build zip crashes Rack

### ISSUE THREAD

**Issue by SteveRussell33** [wlaub/vcv#6]
Selecting any module from the browser = instant crash

Rack v1.0.0
Win 10

**Comment by wlaub** [comment]
Did you build the plugin yourself? I've just learned that I never added the windows build for 1.0 to the releases (https://github.com/wlaub/vcv/tree/master/releases). If you're using the old v0.6 build, then the new 1.0 build might work better.

**Comment by SteveRussell33** [comment]
I did originally.

Both releases crash Rack v113.

**Comment by wlaub** [comment]
I found a computer that reproduces this, and removing Pleiades seems to fix the issue on my end. I'll have to figure out what its deal is, but in the meantime, https://github.com/wlaub/vcv/tree/bugfix/crashing/releases this build might work for you.

**Comment by wlaub** [comment]
Looks like the above fix was a fluke, as it is no longer working on my test machine.

**Comment by smok-e** [comment]
same here, still crashes VCV when I want to load a module

**Comment by wlaub** [comment]
I can't claim to understand why, but I've managed to consistently resolve the issue in one module by updating the syntax for defining param min/max/default values from the 0.6 style (values defined in createParam call in moduleWidget) to the 1.0 style (values defined in module using configParam). I'll post an update here when I've finished porting everything.

**Comment by wlaub** [comment]
Latest build in master should fix all the hand-generated modules (DAC, mDAC, Vulcan, Prometheus, Sisyphus, Ouroboros, Odysseus, Polyphemus, Mneme). Script-generated modules (Achilles, QMod, Pleiades, Convo) may take a bit longer.

**Comment by pgatt** [comment]
Just to confirm here - Achilles, QMod and Convo are still crashing every time. Pleiades has occasionally loaded into my Rack without issue since the last build.

**Comment by SteveRussell33** [comment]
Crashing & master release builds crash Rack whenever a module from the browser is selected

(Log.txt stacktrace)
[13.019 fatal src/main.cpp:38] Fatal signal 11. Stack trace:
25: ZN4rack10appDestroyEv 0x456415
24: gai_strerrorW 0x757ac0
23: _C_specific_handler 0x8e8a7fd0
22: _chkstk 0x91584660
21: RtlWalkFrameChain 0x914e3730
20: KiUserExceptionDispatcher 0x915834c0
19: DrvPresentBuffers 0x12630230
18: ZN4rack6widget6Widget11getViewportENS_4math4RectE 0x4a6b20
17: ZN4rack3app7SvgKnob8onChangeERKNS_5event6ChangeE 0x48fef0
16: ZN4rack3app11ParamWidget4stepEv 0x499326
15: ZN4rack6widget6Widget4stepEv 0x4a72f2
14: ZN4rack6widget6Widget4stepEv 0x4a72f2
13: ZN4rack6widget6Widget4stepEv 0x4a72f2
12: ZN4rack6widget6Widget4stepEv 0x4a72f2
11: ZN4rack6widget6Widget4stepEv 0x4a72f2
10: ZN4rack6widget6Widget4stepEv 0x4a72f2
9: ZN4rack2ui12ScrollWidget4stepEv 0x4a31ce
8: ZN4rack3app16RackScrollWidget4stepEv 0x48b720
7: ZN4rack6widget6Widget4stepEv 0x4a72f2
6: ZN4rack3app5Scene4stepEv 0x491f86
5: ZN4rack6Window3runEv 0x4594ca
4: main 0x7a0000
3: main 0x7a0000
2: main 0x7a0000
1: BaseThreadInitThunk 0x8fec7960
0: RtlUserThreadStart 0x9154a250

**Comment by SteveRussell33** [comment]
I've built a release that has Convo, Achilles and Pleiades removed as these were the modules that were causing my machine to crash.

So far, this custom build is stable.
HTH

**Comment by wlaub** [comment]
As of the latest push to master, everything seems to be working on my end (assuming I didn't just get lucky). Some of these updates haven't been ported to develop yet (that's going to be a fun party).

**Comment by SteveRussell33** [comment]
Your latest release build is stable so far.
Getting somewhere, good job ;)

**Comment by pgatt** [comment]
All except Convo are fine here - Convo does this to my Rack:

[11.500 fatal src/main.cpp:38] Fatal signal 11. Stack trace:
8: 1   Rack                                0x000000010a0d8e29 _ZL18fatalSignalHandleri + 41
7: 2   libsystem_platform.dylib            0x00007fff6beaeb5d _sigtramp + 29
6: 3   ???                                 0x0000000111a87405 0x0 + 4591219717
5: 4   Rack                                0x000000010a12d0b7 _ZN4rack6engineL18Engine_stepModulesEPNS0_6EngineEi + 231
4: 5   Rack                                0x000000010a12cebb _ZN4rack6engine12EngineWorker3runEv + 203
3: 6   Rack                                0x000000010a12e385 _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN4rack6engine12EngineWorker5startEvEUlvE_EEEEEPvSC_ + 53
2: 7   libsystem_pthread.dylib             0x00007fff6beb72eb _pthread_body + 126
1: 8   libsystem_pthread.dylib             0x00007fff6beba249 _pthread_start + 66
0: 9   libsystem_pthread.dylib             0x00007fff6beb640d thread_start + 13

**Comment by smok-e** [comment]
I can't find a compiled win version of the updated master branch.

**Comment by SteveRussell33** [comment]
Here's my local build:
https://drive.google.com/open?id=1qEJotqW4U5FGkDYG02_907vdjVTxU6Eq

**Comment by smok-e** [comment]
Thx Steve, finally I found the compiled versions, I've been looking under the "release"tab

**Comment by SteveRussell33** [comment]
Closing as this thread was for v1
