### ISSUE TITLE
Pleiades

### ISSUE THREAD

**Issue by caecos** [wlaub/vcv#9]
This module crashes VCVRack on Windows 10 Pro... each time I call this module, VCVRack close...

**Comment by wlaub** [comment]
Is the issue only with Pleiades? I recall fixing some instabilities issues overall a while back, and I thought I fixed Pleiades at the same time, but it's a pretty poorly written module so I wouldn't be surprised it still has issues.

**Comment by caecos** [comment]
Yes, only with this module. The others work fine…

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : ***@***.***>
Envoyé le :dimanche 6 juin 2021 19:17
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [wlaub/vcv] Pleiades (#9)


Is the issue only with Pleiades? I recall fixing some instabilities issues overall a while back, and I thought I fixed Pleiades at the same time, but it's a pretty poorly written module so I wouldn't be surprised if it still has issues.

**Comment by wlaub** [comment]
I'll try to find some time to look into it, but it's not a super high priority as pleaides is unfinished and even when it doesn't crash is borderline unusable.

**Comment by wlaub** [comment]
Are you using [this build](https://github.com/wlaub/vcv/blob/master/releases/TechTechTechnologies-1.0.0-win.zip)? Can you provide a copy of the log.txt from your Rack folder after a crash? I haven't been able to reproduce the issue on my end yet.

**Comment by caecos** [comment]
I compiled the source from Github… I will send you the log.txt…

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : wlaub ***@***.***>
Envoyé : Thursday, June 10, 2021 1:39:37 PM
À : wlaub/vcv ***@***.***>
Cc : caecos ***@***.***>; Author ***@***.***>
Objet : Re: [wlaub/vcv] Pleiades (#9)


Are you using this build<https://github.com/wlaub/vcv/blob/master/releases/TechTechTechnologies-1.0.0-win.zip>? Can you provide a copy of the log.txt from your Rack folder after a crash? I haven't been able to reproduce the issue on my end yet.

**Comment by wlaub** [comment]
Pleiades was removed in the process of updating the plugin for v2.
